name: Main CI pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  setup:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup project, python and poetry
        uses: ./setup-action
        with:
          python-version: ${{ matrix.python-version }}
  linting:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    needs: setup
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run Black
        run: |
          source .venv/scripts/activate
          black --check boostbuild
        if: runner.os == 'Windows'
      - name: Run Pylint
        run: |
          source .venv/bin/activate
          pylint --rcfile pyproject.toml boostbuild
        if: runner.os != 'Windows'
  