name: Publish pipeline
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  call-main:
    uses: ./.github/workflows/main.yaml
  publish:
    needs: call-main
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Poetry
      uses: snok/install-poetry@v1
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.10-${{ hashFiles('**/poetry.lock') }}
      - name: Publish package to PyPi
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          source .venv/bin/activate
          boost publish
  