name: Publish pipeline
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup project, python and poetry
        uses: ./setup-action
        with:
          python-version: ${{ matrix.python-version }}
      - name: Publish package to PyPi
        run: poetry publish --build --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
  